<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Statistics Tutorial 2 - Numerical Data</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-introduction" class="section level2">
<h2><strong>Introduction</strong></h2>
<p>In this tutorial, you will learn about numerical data - when our measurements are represented as quantities.</p>
<p>We will use the following R Commands:</p>
<ul>
<li><code>mean()</code></li>
<li><code>median()</code></li>
<li><code>select()</code></li>
<li><code>summarise()</code></li>
<li><code>max()</code></li>
<li><code>min()</code></li>
<li><code>IQR()</code></li>
<li><code>sd()</code></li>
<li><code>var()</code></li>
<li><code>rnorm()</code></li>
<li><code>geom_histogram()</code></li>
<li><code>facet_wrap()</code></li>
</ul>
<p>We will use the following dataset:</p>
<ul>
<li><code>mtcars</code> - <em>Motor Trend Car Road Tests</em>, a dataset that comes preloaded in R, containing data about various cars from 1974.</li>
</ul>
<pre class="r"><code># convert mtcars from dataframe to tibble for easier printing
mtcars &lt;- as_tibble(mtcars)
mtcars </code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mpg"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cyl"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["disp"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["hp"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["drat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["wt"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["qsec"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["vs"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["am"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["gear"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["carb"],"name":[11],"type":["dbl"],"align":["right"]}],"data":[{"1":"21.0","2":"6","3":"160.0","4":"110","5":"3.90","6":"2.620","7":"16.46","8":"0","9":"1","10":"4","11":"4"},{"1":"21.0","2":"6","3":"160.0","4":"110","5":"3.90","6":"2.875","7":"17.02","8":"0","9":"1","10":"4","11":"4"},{"1":"22.8","2":"4","3":"108.0","4":"93","5":"3.85","6":"2.320","7":"18.61","8":"1","9":"1","10":"4","11":"1"},{"1":"21.4","2":"6","3":"258.0","4":"110","5":"3.08","6":"3.215","7":"19.44","8":"1","9":"0","10":"3","11":"1"},{"1":"18.7","2":"8","3":"360.0","4":"175","5":"3.15","6":"3.440","7":"17.02","8":"0","9":"0","10":"3","11":"2"},{"1":"18.1","2":"6","3":"225.0","4":"105","5":"2.76","6":"3.460","7":"20.22","8":"1","9":"0","10":"3","11":"1"},{"1":"14.3","2":"8","3":"360.0","4":"245","5":"3.21","6":"3.570","7":"15.84","8":"0","9":"0","10":"3","11":"4"},{"1":"24.4","2":"4","3":"146.7","4":"62","5":"3.69","6":"3.190","7":"20.00","8":"1","9":"0","10":"4","11":"2"},{"1":"22.8","2":"4","3":"140.8","4":"95","5":"3.92","6":"3.150","7":"22.90","8":"1","9":"0","10":"4","11":"2"},{"1":"19.2","2":"6","3":"167.6","4":"123","5":"3.92","6":"3.440","7":"18.30","8":"1","9":"0","10":"4","11":"4"},{"1":"17.8","2":"6","3":"167.6","4":"123","5":"3.92","6":"3.440","7":"18.90","8":"1","9":"0","10":"4","11":"4"},{"1":"16.4","2":"8","3":"275.8","4":"180","5":"3.07","6":"4.070","7":"17.40","8":"0","9":"0","10":"3","11":"3"},{"1":"17.3","2":"8","3":"275.8","4":"180","5":"3.07","6":"3.730","7":"17.60","8":"0","9":"0","10":"3","11":"3"},{"1":"15.2","2":"8","3":"275.8","4":"180","5":"3.07","6":"3.780","7":"18.00","8":"0","9":"0","10":"3","11":"3"},{"1":"10.4","2":"8","3":"472.0","4":"205","5":"2.93","6":"5.250","7":"17.98","8":"0","9":"0","10":"3","11":"4"},{"1":"10.4","2":"8","3":"460.0","4":"215","5":"3.00","6":"5.424","7":"17.82","8":"0","9":"0","10":"3","11":"4"},{"1":"14.7","2":"8","3":"440.0","4":"230","5":"3.23","6":"5.345","7":"17.42","8":"0","9":"0","10":"3","11":"4"},{"1":"32.4","2":"4","3":"78.7","4":"66","5":"4.08","6":"2.200","7":"19.47","8":"1","9":"1","10":"4","11":"1"},{"1":"30.4","2":"4","3":"75.7","4":"52","5":"4.93","6":"1.615","7":"18.52","8":"1","9":"1","10":"4","11":"2"},{"1":"33.9","2":"4","3":"71.1","4":"65","5":"4.22","6":"1.835","7":"19.90","8":"1","9":"1","10":"4","11":"1"},{"1":"21.5","2":"4","3":"120.1","4":"97","5":"3.70","6":"2.465","7":"20.01","8":"1","9":"0","10":"3","11":"1"},{"1":"15.5","2":"8","3":"318.0","4":"150","5":"2.76","6":"3.520","7":"16.87","8":"0","9":"0","10":"3","11":"2"},{"1":"15.2","2":"8","3":"304.0","4":"150","5":"3.15","6":"3.435","7":"17.30","8":"0","9":"0","10":"3","11":"2"},{"1":"13.3","2":"8","3":"350.0","4":"245","5":"3.73","6":"3.840","7":"15.41","8":"0","9":"0","10":"3","11":"4"},{"1":"19.2","2":"8","3":"400.0","4":"175","5":"3.08","6":"3.845","7":"17.05","8":"0","9":"0","10":"3","11":"2"},{"1":"27.3","2":"4","3":"79.0","4":"66","5":"4.08","6":"1.935","7":"18.90","8":"1","9":"1","10":"4","11":"1"},{"1":"26.0","2":"4","3":"120.3","4":"91","5":"4.43","6":"2.140","7":"16.70","8":"0","9":"1","10":"5","11":"2"},{"1":"30.4","2":"4","3":"95.1","4":"113","5":"3.77","6":"1.513","7":"16.90","8":"1","9":"1","10":"5","11":"2"},{"1":"15.8","2":"8","3":"351.0","4":"264","5":"4.22","6":"3.170","7":"14.50","8":"0","9":"1","10":"5","11":"4"},{"1":"19.7","2":"6","3":"145.0","4":"175","5":"3.62","6":"2.770","7":"15.50","8":"0","9":"1","10":"5","11":"6"},{"1":"15.0","2":"8","3":"301.0","4":"335","5":"3.54","6":"3.570","7":"14.60","8":"0","9":"1","10":"5","11":"8"},{"1":"21.4","2":"4","3":"121.0","4":"109","5":"4.11","6":"2.780","7":"18.60","8":"1","9":"1","10":"4","11":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-numerical-data" class="section level2">
<h2><strong>Numerical Data</strong></h2>
<p>Let’s start out by discussing numerical data - data with measurements that are represented as quantities.</p>
<div id="section-discrete-and-continuous-data" class="section level3">
<h3>Discrete and Continuous Data</h3>
<p>There are two primary categories of numerical data: - <strong>discrete data</strong>: data in which there are no intermediate values between two numbers. - <strong>continuous data</strong>: data in which decimal values allow there to be infinitely many values between two numbers.</p>
<p>The number of children in a household is a common example of discrete data. A household can have 1 or 2 children, but they cannot have 1.5 children.</p>
<p>Temperature is a common example of continuous data. A room can be 70 degrees Fahrenheit, or 70.01 or 70.001…and so on. There are infinitely many values between 70.01 &amp; 70.001. We often “bin” continuous data when visualizing or analyzing it. By that, we mean that we group ranges of values together. For example, we may group all values from 70-75 together when visualizing the daily temperatures experienced in Massachusetts during a summer.</p>
<p>In <code>mtcars</code>, the column <code>wt</code>, which contains the weight of each vehicle (in tons) is a good example of a continuous numerical variable. The column <code>cyl</code>, which contains the number of cylinders in each vehicle’s engine, is a good example of a discrete numerical variable.</p>
<p>Let’s take a look at these two columns.</p>
<pre class="r"><code># selecting wt and cyl to print them
mtcars %&gt;%
  select(wt, cyl) </code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["wt"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cyl"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"2.620","2":"6"},{"1":"2.875","2":"6"},{"1":"2.320","2":"4"},{"1":"3.215","2":"6"},{"1":"3.440","2":"8"},{"1":"3.460","2":"6"},{"1":"3.570","2":"8"},{"1":"3.190","2":"4"},{"1":"3.150","2":"4"},{"1":"3.440","2":"6"},{"1":"3.440","2":"6"},{"1":"4.070","2":"8"},{"1":"3.730","2":"8"},{"1":"3.780","2":"8"},{"1":"5.250","2":"8"},{"1":"5.424","2":"8"},{"1":"5.345","2":"8"},{"1":"2.200","2":"4"},{"1":"1.615","2":"4"},{"1":"1.835","2":"4"},{"1":"2.465","2":"4"},{"1":"3.520","2":"8"},{"1":"3.435","2":"8"},{"1":"3.840","2":"8"},{"1":"3.845","2":"8"},{"1":"1.935","2":"4"},{"1":"2.140","2":"4"},{"1":"1.513","2":"4"},{"1":"3.170","2":"8"},{"1":"2.770","2":"6"},{"1":"3.570","2":"8"},{"1":"2.780","2":"4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The decimal values in <code>wt</code> indicate the continuous nature of the data. There can be a car that weighs 3.01 tons, or 3.001 tons, and so on…On the other hand, <code>cyl</code> is clearly discrete - a car engine cannot have half of a cylinder.</p>
</div>
<div id="section-numerical-data---ordinal-vs.-interval-vs.-ratio" class="section level3">
<h3>Numerical Data - Ordinal vs. Interval vs. Ratio</h3>
<p>Researchers commonly make a distinction between <strong>interval</strong> data, which lacks a true zero, and <strong>ratio</strong> data, which does have a true zero. When data are measured on a ratio scale, a value of 0 indicates a <strong>true absence</strong> of the quantity being measured. Income is an example of ratio data, as it is possible to earn $0 in a fiscal year. This is not true for interval data. For example, a temperature of 0 degrees Fahrenheit does not indicate the absence of temperature - its position is arbitrary. Therefore, temperature is measured on an interval scale.</p>
<p>There’s one more type of numerical data to discuss: <strong>ordinal data</strong>. While ordinal, interval, and ratio data are all rank-ordered (i.e., higher values indicate higher amounts of the quantity being measured), ordinal data <strong>does not assume equal distance between values</strong>. Ordinal data also has no true zero.</p>
<p>For example, you’ve probably filled out a survey where you were asked to rate your satisfaction with a product on a scale from 1-10. While a response of 5 indicates greater satisfaction than a response of 4, there is no way to know if the the difference between 5 and 4 is the same as the difference between 4 and 3. These are convenient values that attempt measure satisfaction approximately but are in no way as precise as measuring temperature with a thermometer. Importantly, there’s no way to know that all processes that generated the observations (e.g., people filing out forms) understand those numbers to mean the same thing.</p>
<p><strong>To summarize:</strong></p>
<ul>
<li><p>Ordinal data</p>
<ul>
<li>rank ordered, can’t assume equal distance between values, have no true zero.</li>
</ul></li>
<li><p>Interval data</p>
<ul>
<li>rank ordered, can assume equal distance between values, have no true zero.</li>
</ul></li>
<li><p>Ratio data</p>
<ul>
<li>rank ordered, can assume equal distance between values, have a true zero.</li>
</ul></li>
</ul>
</div>
</div>
<div id="section-descriptive-statistics---central-tendency" class="section level2">
<h2>Descriptive statistics - Central tendency</h2>
<p>Now we will discuss computing <em>descriptive statistics</em> for numerical data. Descriptive statistics are exactly what they sound like: <em>statistics</em> that <em>describe</em> our sample. They are numerical summaries that convey basic information about our sample of data.</p>
<div id="section-central-tendency" class="section level3">
<h3>Central tendency</h3>
<p>Central tendency is a statistic that describes the center of a distribution of data. The most common measures are the mean, median, and mode. Let’s start out by discussing the mode.</p>
<div id="section-mode" class="section level4">
<h4>Mode</h4>
<p>The mode is the value that is most frequent in a dataset. For example, in the following data, ‘2’ is the most common value, and therefore the mode.</p>
<pre class="r"><code>x &lt;- c(1,2,2,2,5,6,3,2,2,1,2,2)</code></pre>
<p>R does not have a function for computing the mode, so if we wish to do so, we must write one ourselves.</p>
<pre class="r"><code># function for computing the mode of a vector
# find the index of the mode when a table is created
# then use that index on the original vector to find the mode 
compute_mode &lt;- function(x){
  mode_index &lt;- which.max(table(x)) # which.max() returns the index of the max value in a vector
  mode &lt;- x[mode_index] # use the mode_index to find the mode in the original vector
  return(mode)
}
compute_mode(x) # Getting the mode in our original vector</code></pre>
<pre><code>## [1] 2</code></pre>
<p>The mode is a used less frequently than other measures of central tendency. When data are continuous, it’s unlikely that a single mode will even exist. The mode is best used for categorical data (or occasionally discrete numerical data), so it will not be discussed further in this tutorial.</p>
</div>
<div id="section-mean" class="section level4">
<h4>Mean</h4>
<p>The arithmetic mean (colloquially referred to as the average) is the sum of all values in a set of data, divided by the number of values in the data.</p>
<p><span class="math inline">\(\bar{x}=\frac{\Sigma x_{i}}{N}\)</span></p>
<p>We use <span class="math inline">\(\bar{x}\)</span> to refer to a sample mean and <span class="math inline">\(\mu\)</span> to refer to a population mean. The <strong>population</strong> is the entire group we wish to learn about (e.g., all registered voters in America), whereas the <strong>sample</strong> is the subset of that group that we measure in an attempt to learn about the population (e.g., a sample of 200 registered voters that respond to our survey).</p>
<p>Let’s compute the mean weight of the cars in the <code>mtcars</code> dataset.</p>
<pre class="r"><code># Base R method  
# sum adds up all the values, and length gives us the total number of values in the vector
sum(mtcars$wt)/length(mtcars$wt)  </code></pre>
<pre><code>## [1] 3.21725</code></pre>
<pre class="r"><code># Tidyverse method - same operations, but using dplyr syntax
select(mtcars, wt) %&gt;%
  summarise(mean_weight=sum(.)/n()) # sum(.) adds up everything in wt, n() returns the number of observations</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mean_weight"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"3.21725"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>However, there’s an easier way to do it in R. Rather than compute it ourselves, we can have R do it for us using the built-in function <code>mean()</code>.</p>
<pre class="r"><code># Base R method
mean(mtcars$wt) </code></pre>
<pre><code>## [1] 3.21725</code></pre>
<pre class="r"><code># Tidyverse method
mtcars %&gt;%
  summarise(mean_weight=mean(wt)) </code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mean_weight"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"3.21725"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-median" class="section level4">
<h4>Median</h4>
<p>The mean isn’t the only statistic we can use to describe central tendency. We can also compute the median, which is the center-most value when all values in the dataset are arranged in order. For example, in the vector <code>x &lt;- c(1,3,5,6,7)</code>, the number in the middle is 5, so the median is 5.</p>
<p>Averaging the two center-most values is one way of computing the median. For example, in the vector <code>y &lt;- c(1,1,2,3,5,6)</code>, both 2 &amp; 3 are the center-most values, so the median is the average of 2 &amp; 3 (2.5).</p>
<p>We can also use a convenience function in R to compute the median, (i.e., <code>median()</code>).</p>
<pre class="r"><code># Base R
median(mtcars$wt)</code></pre>
<pre><code>## [1] 3.325</code></pre>
<pre class="r"><code># Tidyverse
mtcars %&gt;%
  summarise(median_wt=median(wt))</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["median_wt"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"3.325"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Notice that the median and the mean are very similar here. The mean car weight is 3.21725 tons, while the median car weight is 3.325. This is because the data are not particularly skewed here. We can verify this with a histogram of the car weights.</p>
<pre class="r"><code># using ggplot to create histogram
ggplot(mtcars, aes(wt))+ # wt on the x-axis
  geom_histogram(binwidth = .5,col=&#39;black&#39;,fill=&#39;gray&#39;) # changed more binwidth to be more appropriate</code></pre>
<p><img src="601--Statistics-2_files/figure-html/unnamed-chunk-8-1.png" width="624" /></p>
<p>But what exactly does “skew” mean? For this, we’ll need to go into more detail about visualizing numerical data.</p>
</div>
<div id="section-exercise-1" class="section level4">
<h4>Exercise 1</h4>
<p>Given this sample dataset <code>data_1</code>, use a pipe (<code>%&gt;%</code>) and <code>summarise()</code> to compute the mean and median of the variable <code>value</code>.</p>
<pre class="r"><code>data_1</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["value"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"47"},{"1":"50"},{"1":"63"},{"1":"54"},{"1":"45"},{"1":"43"},{"1":"40"},{"1":"51"},{"1":"51"},{"1":"52"},{"1":"52"},{"1":"48"},{"1":"37"},{"1":"44"},{"1":"65"},{"1":"52"},{"1":"48"},{"1":"45"},{"1":"52"},{"1":"48"},{"1":"44"},{"1":"39"},{"1":"54"},{"1":"44"},{"1":"48"},{"1":"54"},{"1":"53"},{"1":"39"},{"1":"52"},{"1":"56"},{"1":"61"},{"1":"55"},{"1":"46"},{"1":"54"},{"1":"41"},{"1":"43"},{"1":"48"},{"1":"51"},{"1":"51"},{"1":"49"},{"1":"45"},{"1":"50"},{"1":"57"},{"1":"52"},{"1":"45"},{"1":"58"},{"1":"48"},{"1":"50"},{"1":"47"},{"1":"51"},{"1":"44"},{"1":"50"},{"1":"53"},{"1":"42"},{"1":"49"},{"1":"49"},{"1":"54"},{"1":"49"},{"1":"49"},{"1":"53"},{"1":"40"},{"1":"54"},{"1":"47"},{"1":"55"},{"1":"57"},{"1":"55"},{"1":"45"},{"1":"52"},{"1":"52"},{"1":"54"},{"1":"44"},{"1":"49"},{"1":"54"},{"1":"49"},{"1":"58"},{"1":"51"},{"1":"46"},{"1":"40"},{"1":"51"},{"1":"50"},{"1":"52"},{"1":"57"},{"1":"48"},{"1":"45"},{"1":"43"},{"1":"54"},{"1":"47"},{"1":"51"},{"1":"55"},{"1":"34"},{"1":"49"},{"1":"49"},{"1":"49"},{"1":"37"},{"1":"63"},{"1":"54"},{"1":"51"},{"1":"46"},{"1":"50"},{"1":"51"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="tutorial-exercise" data-label="mean-median" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># use summarise to compute mean and median</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.timelimit":10,"exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean-median-solution" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>data_1 %&gt;%
  summarise(
    mean=mean(value),
    median=median(value)
  )</code></pre>
</div>
</div>
</div>
</div>
<div id="section-visualizing-numerical-data" class="section level2">
<h2><strong>Visualizing Numerical Data</strong></h2>
<pre class="r"><code># ADVANCED - Feel free to ignore this code block!
set.seed(230344)
n &lt;- 200
symmetric &lt;- rnorm(n, 75, 15)
right_skew &lt;- symmetric - c(rep(0,10),rep(70,180),rep(0,10))
left_skew &lt;- abs(200-right_skew)
sample_data &lt;- tibble(
  symmetric=symmetric,
  right_skew=right_skew,
  left_skew=left_skew
) %&gt;%
  pivot_longer(
    cols=c(symmetric,right_skew,left_skew),
    names_to = &quot;distribution&quot;,
    values_to = &quot;value&quot;
  ) </code></pre>
<div id="section-understanding-the-shape-of-our-data" class="section level3">
<h3><strong>Understanding the shape of our data</strong></h3>
<p>Researchers often like to create histograms after collecting data measured on a continuous scale. Histograms “bin” values - group values within specific ranges together - and show the frequency with which each bin occurs. Here’s an example, using randomly sampled data.</p>
<pre class="r"><code># setting the seed can be useful for reproducing code results when simulation is involved
set.seed(10000) 
data &lt;- tibble( 
  value=rnorm(100,100,20) # randomly sample 100 values from a normal distribution w/ mean 100 and sd 20
)
ggplot(data, aes(x=value))+ # ggplot with &#39;value&#39; on the x axis
  geom_histogram(binwidth = 10,col=&#39;black&#39;,fill=&#39;white&#39;) # changed binwidth to a more appropriate value</code></pre>
<p><img src="601--Statistics-2_files/figure-html/unnamed-chunk-12-1.png" width="624" /></p>
<p>We randomly sample data from a normal distribution with a mean of 20 and a standard deviation of 15. Then, we create a histogram from these data, with a bin width of 10. This indicates that each bar spans 10 values. We then see the frequency with which each bin occurs. The bin centered around 100 has the highest count, which makes sense because we sampled from a distribution with a mean of 100.</p>
<p>There’s one other crucial thing to point out about this data: it’s (approximately) <strong>symmetrical</strong>. That is to say, there’s essentially an equal amount of data on either side of the mean.</p>
<p>However, sometimes our data will be skewed. By this we mean, there is a long “tail” of values on one side of the distribution that can affect the way we interpret and summarize our data.</p>
<p>Below are examples of symmetric, left, and right-skewed data.</p>
<p><img src="601--Statistics-2_files/figure-html/unnamed-chunk-13-1.png" width="624" /></p>
<p>Looking at our left-skewed data, we see a long tail going out to the <strong>left</strong>. On the other hand, when we look at our right-skewed data, we see a long tail going out to the <strong>right</strong>. Finally, the symmetric data is (approximately) <strong>the same on either side</strong>.Let’s see how this affects our calculation of the mean and median.</p>
<pre class="r"><code>sample_data %&gt;%
  group_by(distribution) %&gt;% # use &#39;distribution&#39; (symmetric, right_skew, and left_skew) as grouping variable
  summarise(
    mean=mean(value), # compute mean
    median=median(value) # compute median
  )</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["distribution"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"left_skew","2":"188.02398","3":"192.78915"},{"1":"right_skew","2":"11.97602","3":"7.21085"},{"1":"symmetric","2":"74.97602","3":"75.46360"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Our summarized data can be used to show how skew affects the mean and median. The symmetric distribution has a mean and median that are nearly identical. On the other hand, the left and right-skewed distributions show some discrepancies between mean and median.</p>
<p>When we look at the right skewed histogram, the center of the data appears to be somewhere around 5-7, which the median confirms. However, the mean is actually much higher, with a value of 12. This is because the skewed values “pull” the mean away from we might think to be the center of the data. If we had blindly calculated the mean without taking a look at our data, we would have come away with a much different idea of the data’s central tendency.</p>
<p>The same thing occurs with our left-skewed data. The median is 193, while the mean (188) is pulled towards the longer left tail.</p>
<p>To summarise: it’s crucial to visually examine your data. If your data exhibits any sort of skew, it’s best to use the median as a measure of central tendency. Otherwise, the mean is usually preferred.</p>
</div>
</div>
<div id="section-descriptive-statistics---variability" class="section level2">
<h2>Descriptive Statistics - Variability</h2>
<div id="section-variability" class="section level3">
<h3>Variability</h3>
<p>Now that we’ve discussed measures of central tendency, we must also discuss measures of <em>variability</em>. Variability generally refers to how different the values in our data are from one another. The first measure of variability is <em>range</em>.</p>
<div id="section-range" class="section level4">
<h4>Range</h4>
<p><em>Range</em> is simply the maximum value in the dataset minus the minimum value in the dataset.</p>
<p><span class="math inline">\(Range=Max-Min\)</span></p>
<p>Going back to <code>mtcars</code>, the range of <code>wt</code> is calculated as follows:</p>
<pre class="r"><code># base R method
max(mtcars$wt)-min(mtcars$wt) # can use max() and min() of wt to compute range</code></pre>
<pre><code>## [1] 3.911</code></pre>
<pre class="r"><code># Tidyverse method
mtcars %&gt;%
  summarise(
    range_wt=max(wt)-min(wt) # can use max() and min() of wt to compute range
  )</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["range_wt"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"3.911"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-interquartile-range-iqr" class="section level4">
<h4>Interquartile Range (IQR)</h4>
<p>You’ve probably learned about quantiles before (also known as percentiles). <em>IQR</em> is simply the range from the 25th quantile to the 75th quantile.</p>
<p><span class="math inline">\(IQR = 75th Percentile - 25th Percentile\)</span></p>
<p>We can compute it easily in R using the <code>IQR()</code> function:</p>
<pre class="r"><code># Base R method
IQR(mtcars$wt) </code></pre>
<pre><code>## [1] 1.02875</code></pre>
<pre class="r"><code># tidyverse method
mtcars %&gt;%
  summarise(
    iqr_wt=IQR(wt)
  )</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["iqr_wt"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"1.02875"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-standard-deviation-sd" class="section level4">
<h4>Standard Deviation (SD)</h4>
<p><em>Standard deviation</em> is a more complex measure of variability, but one that’s far more common in practice than Range or IQR. Standard deviation is essentially the square root of the sum of squared deviations from the mean divided by the sample size. We use the <span class="math inline">\(\sigma\)</span> (sigma) symbol for the population standard deviation (which is usually unknown), and <span class="math inline">\(\hat{\sigma}\)</span> (sigma hat) for the sample standard deviation (which is what we must typically estimate as researchers).</p>
<p><span class="math inline">\(\hat{\sigma} = \sqrt{\frac{\Sigma(x_{i}-\bar{x})^2}{N}}\)</span></p>
<p>We use <span class="math inline">\(\hat{\sigma}\)</span> to refer to a sample standard deviation and <span class="math inline">\(\sigma\)</span> to refer to a population standard deviation.</p>
<p>Standard deviation is best interpreted using the 68-95-99.7 rule - given the assumption that our data are normally distributed, 68% of our data will fall within 1 standard deviation of the mean, 95% of our data will fall within 2 standard deviations of the mean, and 99.7% of our data will fall within 3 standard deviations of the mean.</p>
<p>Standard deviation can be computed in R using the <code>sd()</code> function.</p>
<pre class="r"><code># Base R method
sd(mtcars$wt)</code></pre>
<pre><code>## [1] 0.9784574</code></pre>
<pre class="r"><code># Tidyverse method
mtcars %&gt;%
  summarise(
    sd_wt=sd(wt)
  )</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["sd_wt"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.9784574"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-variance" class="section level4">
<h4>Variance</h4>
<p>The last measure of variability is <em>variance</em>. Variance is simply the sum of squared deviations from the mean divided by sample size. In other words, it is the same as standard deviation but without the square root. We use <span class="math inline">\(\sigma^{2}\)</span> to indicate population variance and <span class="math inline">\(\hat{\sigma^{2}}\)</span> to indicate sample variance.</p>
<p><span class="math inline">\(\hat{\sigma^{2}} = \frac{\Sigma(x_{i}-\bar{x})^2}{N}\)</span></p>
<p>While variance is crucial for many mathematical aspects of statistics (which you will learn more about in the future), standard deviation is often much easier to interpret.</p>
<p>Variance can be computed in R using the <code>var()</code> function.</p>
<pre class="r"><code># Base R method
var(mtcars$wt)</code></pre>
<pre><code>## [1] 0.957379</code></pre>
<pre class="r"><code># Tidyverse method
mtcars %&gt;%
  summarise(
    var_wt=var(wt)
  )</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["var_wt"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.957379"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-exercise-2" class="section level4">
<h4>Exercise 2</h4>
<p>Again using <code>data_1</code>, compute the variance and standard deviation of <code>value</code> using <code>summarise()</code>.</p>
<pre class="r"><code>data_1</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["value"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"47"},{"1":"50"},{"1":"63"},{"1":"54"},{"1":"45"},{"1":"43"},{"1":"40"},{"1":"51"},{"1":"51"},{"1":"52"},{"1":"52"},{"1":"48"},{"1":"37"},{"1":"44"},{"1":"65"},{"1":"52"},{"1":"48"},{"1":"45"},{"1":"52"},{"1":"48"},{"1":"44"},{"1":"39"},{"1":"54"},{"1":"44"},{"1":"48"},{"1":"54"},{"1":"53"},{"1":"39"},{"1":"52"},{"1":"56"},{"1":"61"},{"1":"55"},{"1":"46"},{"1":"54"},{"1":"41"},{"1":"43"},{"1":"48"},{"1":"51"},{"1":"51"},{"1":"49"},{"1":"45"},{"1":"50"},{"1":"57"},{"1":"52"},{"1":"45"},{"1":"58"},{"1":"48"},{"1":"50"},{"1":"47"},{"1":"51"},{"1":"44"},{"1":"50"},{"1":"53"},{"1":"42"},{"1":"49"},{"1":"49"},{"1":"54"},{"1":"49"},{"1":"49"},{"1":"53"},{"1":"40"},{"1":"54"},{"1":"47"},{"1":"55"},{"1":"57"},{"1":"55"},{"1":"45"},{"1":"52"},{"1":"52"},{"1":"54"},{"1":"44"},{"1":"49"},{"1":"54"},{"1":"49"},{"1":"58"},{"1":"51"},{"1":"46"},{"1":"40"},{"1":"51"},{"1":"50"},{"1":"52"},{"1":"57"},{"1":"48"},{"1":"45"},{"1":"43"},{"1":"54"},{"1":"47"},{"1":"51"},{"1":"55"},{"1":"34"},{"1":"49"},{"1":"49"},{"1":"49"},{"1":"37"},{"1":"63"},{"1":"54"},{"1":"51"},{"1":"46"},{"1":"50"},{"1":"51"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="tutorial-exercise" data-label="sd-var" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># use summarise to compute sd and variance</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.timelimit":10,"exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="sd-var-solution" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>data_1 %&gt;%
  summarise(
    sd=sd(value),
    var=var(value)
  )</code></pre>
</div>
</div>
</div>
</div>
<div id="section-conclusion" class="section level2">
<h2>Conclusion</h2>
<p>You have now learned about types of numerical data, visualizing numerical data, and ways to measure central tendency and variability in numerical data.</p>
<div id="section-references" class="section level3">
<h3><strong>References</strong></h3>
<p>Navarro, D. J. (2015). <em>Learning Statistics with R: A Tutorial for Psychology Students and Other Beginners</em>, Version 0.6.</p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(tidyverse)
library(knitr)
opts_chunk$set(echo = TRUE)
tutorial_options(exercise.timelimit = 10)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean-median-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean-median-code-editor`)), session)
output$`tutorial-exercise-mean-median-output` <- renderUI({
  `tutorial-exercise-mean-median-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-sd-var-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-sd-var-code-editor`)), session)
output$`tutorial-exercise-sd-var-output` <- renderUI({
  `tutorial-exercise-sd-var-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["header-attrs"]},{"type":"character","attributes":{},"value":["2.9"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pandoc"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["header-attrs.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.9"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","bslib","cellranger","cli","colorspace","compiler","crayon","datasets","DBI","dbplyr","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","forcats","fs","generics","ggplot2","glue","graphics","grDevices","grid","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","httr","jquerylib","jsonlite","knitr","labeling","later","learnr","lifecycle","lubridate","magrittr","markdown","methods","mime","modelr","munsell","pillar","pkgconfig","promises","purrr","R6","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","sass","scales","shiny","stats","stringi","stringr","tibble","tidyr","tidyselect","tidyverse","tools","utf8","utils","vctrs","withr","xfun","xml2","xtable","yaml"]},{"type":"character","attributes":{},"value":["0.2.1","1.2.1","4.1.0","0.7.7","0.2.5.1","1.1.0","2.5.0","2.0-1","4.1.0","1.4.1","4.1.0","1.1.1","2.1.1","0.6.27","1.0.6","0.3.2","0.14","0.5.0","2.1.0","1.1.0","0.5.1","1.5.0","0.1.0","3.3.4","1.4.2","4.1.0","4.1.0","4.1.0","0.3.0","2.4.1","0.9","1.1.0","0.5.1.1","1.5.3","1.6.1","1.4.2","0.1.4","1.7.2","1.33","0.4.2","1.2.0","0.10.1","1.0.0","1.7.10","2.0.1","1.1","4.1.0","0.10","0.1.8","0.5.0","1.6.1","2.0.3","1.2.0.1","0.3.4","2.5.0","1.0.6","1.4.0","1.3.1","2.0.0","0.4.11","2.9","2.0.2","0.13","1.0.0","0.4.0","1.1.1","1.6.0","4.1.0","1.6.2","1.4.0","3.1.2","1.1.3","1.1.1","1.3.1","4.1.0","1.2.1","4.1.0","0.3.8","2.4.2","0.24","1.3.2","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Statistics Tutorial 2 - Numerical Data</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
